#ifndef COAPI_CLARA_H_
#define COAPI_CLARA_H_

#ifdef __cplusplus
extern "C" {
#endif

typedef enum clara_keywords_enum {
    CLARA_KEYWORDS_WAKEUP_WORD_1 = 0,
    CLARA_KEYWORDS_WAKEUP_WORD_2,
    CLARA_KEYWORDS_WAKEUP_WORD_3,
    CLARA_KEYWORDS_WAKEUP_WORD_4,

    CLARA_KEYWORDS_COMMAND_LIGHT_ON    = 4,
    CLARA_KEYWORDS_COMMAND_LIGHT_OFF,
    CLARA_KEYWORDS_COMMAND_DRAPES_ON,
    CLARA_KEYWORDS_COMMAND_DRAPES_OFF,
    CLARA_KEYWORDS_COMMAND_AIR_CONDITIONER_ON,
    CLARA_KEYWORDS_COMMAND_AIR_CONDITIONER_OFF,
    CLARA_KEYWORDS_COMMAND_TEMPERATURE_UP,
    CLARA_KEYWORDS_COMMAND_TEMPERATURE_DOWN,
    CLARA_KEYWORDS_COMMAND_UNDERFLOOR_HEATING_ON,
    CLARA_KEYWORDS_COMMAND_UNDERFLOOR_HEATING_OFF,
    CLARA_KEYWORDS_COMMAND_FRESH_AIR_ON,
    CLARA_KEYWORDS_COMMAND_FRESH_AIR_OFF,
    CLARA_KEYWORDS_COMMAND_WARM_MODE,
    CLARA_KEYWORDS_COMMAND_BRIGHT_MODE,
    CLARA_KEYWORDS_COMMAND_HOME_MODE,
    CLARA_KEYWORDS_COMMAND_LEAVE_HOME_MODE,
    CLARA_KEYWORDS_COMMAND_VOLUME_UP,
    CLARA_KEYWORDS_COMMAND_VOLUME_DOWN,
    CLARA_KEYWORDS_COMMAND_PLAYER_PAUSE,
    CLARA_KEYWORDS_COMMAND_PLAYER_RESUME,

    CLARA_KEYWORDS_END
}clara_keywords_t;

typedef enum _PCM_DATA_TYPE_{
    IS_FIRST_PCM_DATA = 0, 
    IS_ONLY_CLOUD_PCM_DATA,                 /* 数据只传输到 云端 */
    IS_CLARA_CLOUD_PCM_DATA,                /* 数据传输到 云端和clara */
    IS_NORMAL_PCM_DATA,
    IS_LAST_PCM_DATA,
    PCM_DATA_TYPE_END
}pcm_data_type_t;

int clara_keywords_process(clara_keywords_t keywords_type, pcm_data_type_t* p_clara_frame_in_type);


#ifdef __cplusplus
}
#endif

#endif